version: "3.9"

services:
  api:
    build: ./src/PluginStore.Api
    ports:
      - "5100:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    entrypoint: ["dotnet", "PluginStore.Api.dll"]
    depends_on:
      - migration
      - db
  
  migration:
    build: ./src/PluginStore.Api
    entrypoint: ["dotnet", "PluginStore.Api.dll", "/seed"]
    depends_on:
      - db
  
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "PluginStore.Api"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty123"
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  db: